/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { LostItem } from "./LostItem";
import { LostItemCountArgs } from "./LostItemCountArgs";
import { LostItemFindManyArgs } from "./LostItemFindManyArgs";
import { LostItemFindUniqueArgs } from "./LostItemFindUniqueArgs";
import { CreateLostItemArgs } from "./CreateLostItemArgs";
import { UpdateLostItemArgs } from "./UpdateLostItemArgs";
import { DeleteLostItemArgs } from "./DeleteLostItemArgs";
import { User } from "../../user/base/User";
import { LostItemCreateInputDto } from "../LostItemCreateInputDto";
import { LostItemService } from "../lostItem.service";
@graphql.Resolver(() => LostItem)
export class LostItemResolverBase {
  constructor(protected readonly service: LostItemService) {}

  async _lostItemsMeta(
    @graphql.Args() args: LostItemCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [LostItem])
  async lostItems(
    @graphql.Args() args: LostItemFindManyArgs
  ): Promise<LostItem[]> {
    return this.service.lostItems(args);
  }

  @graphql.Query(() => LostItem, { nullable: true })
  async lostItem(
    @graphql.Args() args: LostItemFindUniqueArgs
  ): Promise<LostItem | null> {
    const result = await this.service.lostItem(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => LostItem)
  async createLostItem(
    @graphql.Args() args: CreateLostItemArgs
  ): Promise<LostItem> {
    return await this.service.createLostItem({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => LostItem)
  async updateLostItem(
    @graphql.Args() args: UpdateLostItemArgs
  ): Promise<LostItem | null> {
    try {
      return await this.service.updateLostItem({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => LostItem)
  async deleteLostItem(
    @graphql.Args() args: DeleteLostItemArgs
  ): Promise<LostItem | null> {
    try {
      return await this.service.deleteLostItem(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: LostItem): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.Query(() => String)
  async ReportLostItem(
    @graphql.Args()
    args: string
  ): Promise<string> {
    return this.service.ReportLostItem(args);
  }

  @graphql.Mutation(() => LostItemCreateInputDto)
  async ReportLostItemAction(
    @graphql.Args()
    args: LostItemCreateInputDto
  ): Promise<LostItemCreateInputDto> {
    return this.service.ReportLostItemAction(args);
  }

  @graphql.Query(() => String)
  async SearchLostItems(
    @graphql.Args()
    args: string
  ): Promise<string> {
    return this.service.SearchLostItems(args);
  }

  @graphql.Query(() => [LostItemCreateInputDto])
  async SearchLostItemsAction(
    @graphql.Args()
    args: string
  ): Promise<LostItemCreateInputDto[]> {
    return this.service.SearchLostItemsAction(args);
  }
}
